VIA_ENABLE = yes
VIAL_ENABLE = yes

EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes

ENCODER_MAP_ENABLE = yes

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no 
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = no




OLED_ENABLE = yes
OLED_DRIVER = SSD1306

#disabled for space
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
SWAP_HANDS_ENABLE = no

QMK_SETTINGS = no
SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
MUSIC_ENABLE = no
